### ISSUE TITLE
Poor performance when exiting map

### ISSUE THREAD

**Issue by twoface1556** [miicck/dont-get-lost#3]
i tought ot add it but i thinbk yall allreadu know. tyhe game is not using al lof the prefomance it can from y pc mostly 20% of it. this results in 20-40fps with low settings even. 

pc: amd 5800x, 3080ti, 16gb

**Comment by Coffee4cr** [comment]
We've noticed slowdowns when we had too many paths (we actually built our whole flooring with paths).
After switching it to like a single pathway to get to places, performance went back up.

**Comment by Coffee4cr** [comment]
I actually figured out a huge Performance issue, 
When you open the map, and zoom out, your FPS drops like crazy, zooming out on the map changes the view distance in the settings.
So if you're zoomed out a lot on the map, and close the map, you'll notice your FPS tanking, go look in your settings and you'll notice your view distance is probably over 200 instead of like ~100

**Comment by miicck** [comment]
I've renamed this issue to track specifically the poor performance when exiting the map with a large render range.

**Comment by miicck** [comment]
Mitigated by: a315995612c0d152a7d6a74daf9b0fcac7caa6be
