### ISSUE TITLE
Dynamite not working

### ISSUE THREAD

**Issue by riccsty** [miicck/dont-get-lost#30]
since resources are infinite the only way to get rid of trees is the dynamite item but if i open menu or look away they come back it might have to do with seed generation or the way the game loads things in

**Comment by miicck** [comment]
Thanks for the report. Dynamite was always an experimental addition, I have decided to make it unobtainable 57425fd8545ad7a69216ebc871c6076e785f9d94. It can still be spawned in. One of the core ideas for the game was that it was fun to build with/around the terrain/objects rather than bulldoze everything to get a nice flat place to build. Thoughts welcome though :)
