### ISSUE TITLE
able to climb all walls

### ISSUE THREAD

**Issue by twoface1556** [miicck/dont-get-lost#4]
every wall that isint angled inword but upto 90 degrees you can jum,p up it with ease.

**Comment by Coffee4cr** [comment]
Hope it's a feature and not a bug :)

**Comment by TacoShower** [comment]
I honestly enjoy this but it's up to @miicck if it's a feature or a bug. I found it super fun to be able to climb trees this way

**Comment by miicck** [comment]
Thanks for the report. I think the general sentiment on forums/discord is that the wall climbing is a feature rather than a bug (it was also by design - I like being able to zoom around). I could add a toggle somewhere to disable it, if people wanted a more "realistic" experience - I'll leave the issue open for now for discussion.

**Comment by miicck** [comment]
See previous comment - community sentiment is that this is a feature, not a bug.
