### ISSUE TITLE
Several items break/disable the (Tab)-InfoScreen, until you move them around

### ISSUE THREAD

**Issue by Madrawn** [miicck/dont-get-lost#42]
Several Items in my inventar don't show a info screen when I press tab, while hovering over them in my inventory, and the info screen will not show up for all other items afterwards. This is fixed by picking the item up and just placing it back inside the inventory, then the tab-screen works again for other items.

See this video for clarity:

https://user-images.githubusercontent.com/1095756/221004557-c1ba6a43-3aa1-4ffd-89aa-14a62c82c9cf.mov

Items that I found that behave in such a way are:
Tool rack, dining table, cabbage planter, catapult, bed, drop-off point, market stall, pantrie.

All other items I currently have in my inventory in the video work without a problem.

The item that first "broke" the info screen is the one that has to be moved to fix it, so if I press tab for e.g. over catapult and then over bed, picking up bed doesn't help, only if I pick up catapult it starts working again. If I reverse the order, only picking up the beds fixes it.

[Da Welt.zip](https://github.com/miicck/dont-get-lost/files/10816894/Da.Welt.zip) My save incase it's only happening for me.

**Comment by miicck** [comment]
Thanks for the detailed report! Fixed in 5e68ff76a4b148bc45843e925a267be0378722da. Turns out this happens with specific items that try to access inspection text that is normally only available when the item has been placed in the world. I've added a flag to player_inspectable that is set when triggered from inside an inventory, which can be used to selectively disable inspection text adders.
